### ISSUE TITLE
[Suggestion] Universal Terminal recipe adjustments

### ISSUE THREAD

**Issue by RubyRezal** [Mari023/AE2WirelessTerminalLibrary#120]
I love the idea of adding functions to the wireless terminal so we don't have to carry multiple wireless terminals, but the current recipes seem like a lot of redundant componants get thrown away in the process.

We get an additional terminal and 2 card slots, which makes it seem like the extra Dense Energy Cell and Wireles Receiver just get thrown away.  It doesn't seem like we get any range increase from multiple antennas and we don't get any energy storage increase for the energy cells.

Convenience should come at a cost, but the cost of the current recipes don't make much sense to me.

As an alternative, I'd like to suggest changing the crafting recipes (or adding alternates) to use just the additional terminal panel and maybe a Calculation Processor or Engineering Processor for the additional card slots?

**Comment by Mari023** [comment]
The energy storage should increase with the installed terminals since versions 10.0.0 (if it doesn't it would be a bug)

The antennas however are currently wasted.
Increasing the range and/or power sounds like a reasonable thing to do and I will look into that.

It was technically possible to add recipes where any single item could be used instead of terminals, but I think I broke it when I changed it to copy upgrades and energy properly and change maximum energy
(It now expects a WirelessTerminalItem)

**Comment by Xastabus** [comment]
The total energy storage capacity does not increase when wireless terminals are combined or added to the Universal terminal.
![2022-01-25_12 44 19](https://user-images.githubusercontent.com/1816386/151030949-051fb5ec-cf72-45d1-a861-677b9388e6e6.png)
![2022-01-25_12 44 21](https://user-images.githubusercontent.com/1816386/151030962-d62854cb-11d9-4584-a10d-2c084fa7381d.png)
![2022-01-25_12 44 24](https://user-images.githubusercontent.com/1816386/151030979-5fe9e66b-3e38-4ccc-9220-5c8325e6fc9f.png)

**Comment by Mari023** [comment]
Interesting
It doesn't set the max power if no upgrades are installed.
It does update once you put in an upgrade via the GUI...

**Comment by Mari023** [comment]
I think a couple of Wireles Receivers are a smal price for the added convenience of having all terminals in one item
