### ISSUE TITLE
[1.19.2 - Forge] Can't use JEI or REI to quickly move items for recipes.

### ISSUE THREAD

**Issue by WhitePhant0m** [Mari023/AE2WirelessTerminalLibrary#155]
![image](https://user-images.githubusercontent.com/33400200/188238468-555c9a84-192a-4425-83cf-25a135bddce4.png)
Gives the above with REI, doesn't show the button on JEI.

Mod ver - 12.1.0

Default AE2 wireless crafting terminal allows item move for recipes.

**Comment by Mari023** [comment]
I forgot the annotation for the JEI plugin, adding it fixes it with JEI.
I couldn't get it working with REI tho, I think it might be an ae2 bug since it doesn't work in the wired crafting terminal either (both with or without REIs JEI compat)
(It does work for the pattern encoding terminal tho)

It will work with JEI in the next release
