### ISSUE TITLE
Wireless terminal shortcut should close inventory

### ISSUE THREAD

**Issue by jeytee84** [Mari023/AE2WirelessTerminalLibrary#194]
A bit of a nekro sidenote to [Issue #29](https://github.com/Mari023/AE2WirelessTerminalLibrary/issues/29): When opening the inventory with the default E key, E also closes the inventory. When trying to replace the inventory with the Wireless Terminal and setting the shortcut for it instead to E, the E key no longer closes the inventory.

**Comment by Mari023** [comment]
this is mostly an ae2 issue, since it handles the hotkeys.

I was pretty sure this was asked there already, but I can't find the post.

I think it is somewhat problematic, since depending on the key used, this can accidentally close the screen when trying to search for anything containing the key

I will however ask the ae2 devs about this, ad move the issue if necessary.
