### ISSUE TITLE
Explain Quantum Bridge Card

### ISSUE THREAD

**Issue by Zenthae** [Mari023/AE2WirelessTerminalLibrary#208]
Hello,
Can you explain how to use the Quantum Bridge Card ?
I put the card in the terminal with one of the singularity.
I built a quantum bridge ring with the other singularity inside.
But now, whenever I leave the wireless range, I can open the terminal, but there are no items.

**Comment by Mari023** [comment]
most likely, your system doesn't have a large enough energy buffer.
try adding an energy cell

**Comment by Notarin** [comment]
+1, just came across this problem myself

**Comment by PrincessRTFM** [comment]
Minor necro, but it would also be nice to have some kind of (ideally in-game) documentation on what the card _does_, because I just found this by spending a while searching for some clue of the purpose behind it. It _sounds_ like it's also supposed to charge the wireless terminal apparently? But I have no idea if it does anything else, or what might set it apart from just using the infinity booster in a wireless access point.

**Comment by sarisman84** [comment]
Ditto. Maybe use the API that Applied Energistics itself uses to include some entries on this mod's features if possible!

**Comment by Mari023** [comment]
> Ditto. Maybe use the API that Applied Energistics itself uses to include some entries on this mod's features if possible!

see #189 
it is planned, but someone has to write it

**Comment by sarisman84** [comment]
Noted! Good to know that its in the works!
