### ISSUE TITLE
ExtendedAE support

### ISSUE THREAD

**Issue by WhitePhant0m** [Mari023/AE2WirelessTerminalLibrary#257]
ExtendedAE adds an Extended Pattern Access Terminal, which has some nice features which the regular version doesn't have, the mod also adds a wireless terminal for it, could support for it be added?

https://www.curseforge.com/minecraft/mc-mods/ex-pattern-provider
https://github.com/GlodBlock/ExtendedAE

**Comment by Mari023** [comment]
since ExtendedAE 1.20-1.0.17-forge, ExtendedAE already has an integration with ae2wtlib, and you can add their terminal to the wireless universal terminal, and use the quantum bridge card

**Comment by WhitePhant0m** [comment]
Oh? on the fabric version as well?

**Comment by WhitePhant0m** [comment]
Though now that I look at it again, support for this mod is coming for ExtendedAE, right? Sorry for wasting your time.
Assumed support had to come from here due to the dev stating the support would have to come from this side in one feature request.

**Comment by Mari023** [comment]
> Oh? on the fabric version as well? Since I tried to add it to the universal terminal on AoF7 2.0.1 and it didn't go in.

I don't think the fabric version has it.
In fact, I don't think the fabric version of ExtendedAE has the wireless Extended Pattern Access Terminal at all

> Though now that I look at it again, support for this mod is coming for ExtendedAE, right? Sorry for wasting your time.
Assumed support had to come from here due to the dev stating the support would have to come from this side in one feature request.

It is okay asking here, since this is about a mod interaction that affects both mods :)

**Comment by WhitePhant0m** [comment]
Fabric version does have the wireless version just can't be put into the universal teminal.
