### ISSUE TITLE
Wireless Pattern Encoding Terminal does not work with JEI on Processing

### ISSUE THREAD

**Issue by ZHENGLOC** [Mari023/AE2WirelessTerminalLibrary#273]
Just like #270 
<img width="812" alt="image" src="https://github.com/Mari023/AE2WirelessTerminalLibrary/assets/24859848/1d386c66-1b98-405b-b552-f0861f284b51">

[crash-2024-05-26_07.02.56-client.txt](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/15446492/crash-2024-05-26_07.02.56-client.txt)
[latest.log](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/15446493/latest.log)

**Comment by Mari023** [comment]
does it work with the normal  (non wireless) pattern encoding terminal?

**Comment by ZHENGLOC** [comment]
> does it work with the normal (non wireless) pattern encoding terminal?

yes, only wireless can't work

**Comment by Mari023** [comment]
that is weird, but it means it is probably fixable on my end

**Comment by Mari023** [comment]
this seems to be specific to GregTech-Modern recipes.

what I think is happening, is that transfer handlers registered via jei cannot interact with recipe registered directly to emi.
in order to fix this, GregTech-Modern add a transfer handler for ae2 themself (https://github.com/GregTechCEu/GregTech-Modern/blob/d8b5cdf8ff4dfb74890c01bdfbe115618280b7f9/src/main/java/com/gregtechceu/gtceu/integration/emi/GTEMIPlugin.java#L46-L48)

I think it should be possible for them to make it work with ae2wtlib too, by adding the same handler for `WETMenu.TYPE` when ae2wtlib is present

I will open an issue on the GregTech-Modern issue tracker about this

**Comment by Mari023** [comment]
fixed by https://github.com/GregTechCEu/GregTech-Modern/pull/1338
