### ISSUE TITLE
latest ae2wtl doesn't support latest ae2

### ISSUE THREAD

**Issue by Monster-Zer0** [Mari023/AE2WirelessTerminalLibrary#50]
there appears to be a hard requirement for 8.2.0-alpha3 and not able to be used with latest ae2

**Comment by Mari023** [comment]
I currently maintain two versions: 1.0.x-xxx versions which work for ae2 8.2.0-alpha.3 and
1.1.x-xxx versions which work for ae2 8.3.0-alpha.1 and higher
this is due internal changes in ae2.
I still primarily maintain the 8.2.0-alpha.3 version since I am not quite sure how stable the new ones are.
ae2 8.3.0-alpha.1 came with a big warning sign to probably not use (yet)
ae2 8.3.0-alpha.2 fixed some bugs, but will still support 8.2.0-alpha.3 (for now)
